version: '2'
services:
    scrapergateway-app:
        image: scrapergateway
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${simlife.registry.password}@simlife-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${simlife.registry.password}@simlife-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://scrapergateway-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=ScraperGateway
            - SIMLIFE_SLEEP=30 # gives time for the Simlife Registry to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=scrapergateway-elasticsearch:9300
        ports:
            - 8080:8080
    scrapergateway-mongodb:
        extends:
            file: mongodb.yml
            service: scrapergateway-mongodb
    scrapergateway-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: scrapergateway-elasticsearch
    simlife-registry:
        extends:
            file: simlife-registry.yml
            service: simlife-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
