version: '2'
services:
    scrapergateway-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/simlife/ScraperGateway/mongodb/:/data/db/
